# AIExam Plus 配置文件

# AI模型API配置
api:
  deepseek:
    api_key: "sk-a8eb2ffd678a48098548942efbf19eea"
    base_url: "https://api.deepseek.com"
    model: "deepseek-coder"
  qwen:
    api_key: "sk-0dfb66cee9fb48708ec6204e78e67c51"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "qwen3-235b-a22b"
  qwen_vl:
    api_key: "sk-0dfb66cee9fb48708ec6204e78e67c51"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "qwen-vl-max"

# 数据存储路径配置
paths:
  input:
    images: "./data/input/images"
  output:
    base: "./data/output"
    logs: "./data/output/logs"

# 机器人属性配置
robot:
  com_port: "COM4"
  baudrate: 115200
  # speed_mode: 2

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation: "1 day"
  max_files: 7
