# P340_AI Configuration

# AI Model API Config
api:
  deepseek:
    api_key: 
    base_url: "https://api.deepseek.com"
    model: "deepseek-coder"
  qwen:
    api_key: 
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "qwen3-235b-a22b"
  qwen_vl:
    api_key: 
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "qwen-vl-max"

# Camera Config
camera:
  id: 0

# Path Config
paths:
  input:
    base: "./data/input"
    images: "./data/input/images"
  output:
    base: "./data/output"
    logs: "./data/output/logs"

# Robot Config
robot:
  com_port:                           # COM port number
  baudrate: 115200                    # Baud rate
  z_up: -18                           # Pen up height (robot arm coordinates)
  z_down: -23                         # Pen down height (robot arm coordinates)
  speed_move: 50                      # Movement speed (when not writing)
  speed_write: 30                     # Writing speed
  origin_x: 384.05                    # Default X coordinate (robot arm position when at top-left corner of A4 paper)
  origin_y: -105                      # Default Y coordinate (robot arm position when at top-left corner of A4 paper)

# Logging Config
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation: "1 day"
  max_files: 7

# Assets Config
assets:
  chinese_fonts: "./assets/Chinese_strokes"